version: '3.9'
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME:-securedb}
      MYSQL_USER: ${DB_USER:-secureuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-securepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-securedb}
      DB_USER: ${DB_USER:-secureuser}
      DB_PASSWORD: ${DB_PASSWORD:-securepass}
      JWT_SECRET: ${JWT_SECRET:-ZmFrZV9zZWNyZXRfY2hhbmdldGhpcy10b2ludGVuZC1iYXNlNjQ=}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-900000}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:4200}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL:-http://localhost:4200}
      MAIL_HOST: ${MAIL_HOST:-mailhog}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH:-false}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS:-false}
      MAIL_SMTP_STARTTLS_REQUIRED: ${MAIL_SMTP_STARTTLS_REQUIRED:-false}
      MAIL_SMTP_SSL_TRUST: ${MAIL_SMTP_SSL_TRUST:-smtp.gmail.com}
      MAIL_DEBUG: ${MAIL_DEBUG:-false}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      MAIL_FROM: ${MAIL_FROM:-no-reply@bna.local}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
